<a href="https://colab.research.google.com/github/BenNguyen1203/Knowledge-Hub/blob/main/Learning-Hub/PyTorch%20for%20Deep%20Learning%20%26%20Machine%20Learning/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

## Importing libraries

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

Documentation: https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar
# Dimension of scalar -> return 0
scalar.ndim
# Get tensor back as Python int -> return 7
scalar.item()

tensor(7)

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector
# Dimension of vector -> return 1
vector.ndim
# Shape/Size of vector -> return 2
vector.shape

tensor([7, 7])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8 ],
                       [9, 10]])
MATRIX
# Dimension of MATRIX -> return 2
MATRIX.ndim
# Return 1st value -> return tensor([9, 10])
MATRIX[1]
# # Shape/Size of MATRIX -> return torch.Size([2, 2])
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.ndim # -> return 3 a.k.a number of square brackets
TENSOR.shape # -> return torch.Size([1, 3, 3]) a.k.a 1 value inside outer bracket, 3 values inside middle bracket, 3 values inside inner bracket
             # -> outer bracket is dim 0, middle bracket is dim 1, inner bracket is dim 2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [5]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor
random_tensor.ndim # return 2 ak.a 2 brackets

4

In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim # result -> (torch.Size([3, 224, 224]), 3)

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

### Creating a range of tensors and tensors-like

In [10]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten # -> tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

random_arange = torch.arange(start=0, end=1000, step=77)
random_arange # -> tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [11]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros # -> tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [15]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor # -> tensor([3., 6., 9.])
float_32_tensor.dtype # -> torch.float32

# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)   # Or float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor # -> tensor([3., 6., 9.], dtype=torch.float16)
float_16_tensor.dtype # -> torch.float16

torch.float16

## Progress

2:03:26